apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: globomantics-hotel-dev

resources:
- ../../base
- namespace.yaml
- tls-secret.yaml

patchesStrategicMerge:
- patches/ingress.yaml
- patches/configmap.yaml
- patches/namespace.yaml
- patches/frontend-deployment.yaml
- patches/backend-deployment.yaml

images:
- name: excelsior-3868/globomantics-be:v7
  newName: ghcr.io/excelsior-3868/globomantics-hotel-backend
  newTag: 98f6cfd5f4a0850d238ced82de6f805cb0c57d26
- name: excelsior-3868/globomantics-fe:v4
  newName: ghcr.io/excelsior-3868/globomantics-hotel-frontend
  newTag: 98f6cfd5f4a0850d238ced82de6f805cb0c57d26


