apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: globomantics-hotel-dev

resources:
- ../../base
- namespace.yaml
- tls-secret.yaml

patchesStrategicMerge:
- patches/ingress.yaml
- patches/configmap.yaml
- patches/namespace.yaml
- patches/frontend-deployment.yaml
- patches/backend-deployment.yaml

images:
- name: excelsior-3868/globomantics-be:v7
  newName: ghcr.io/excelsior-3868/globomantics-hotel-backend
  newTag: 90d13a48e9153ed87b40b7d6cff73512e7de345c
- name: excelsior-3868/globomantics-fe:v4
  newName: ghcr.io/excelsior-3868/globomantics-hotel-frontend
  newTag: 90d13a48e9153ed87b40b7d6cff73512e7de345c
