apiVersion: v1
kind: Secret
metadata:
  name: guestbook-backend-secret
data:
  mongodb-username: "YWRtaW4="
  mongodb-password: "cGFzc3dvcmQ="
  s3-access-key: "NjVQWVhBM0RNQVFETFpJVDA1WVY="
  s3-secret-key: "YW0rSXpWWVpNS05laVJsQktZTGhWazR2RnNGOVYxeDA2ZUNXOGgyWA=="
